name: angular CI
on:
  
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"
        type: boolean
        default: true
      node-version:
        description: "Select Node.js version"
        type: choice
        options:
          - '18.x'
          - '20.x'
        default: '20.x'

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate Cache-key
        id: cache-key
        run: echo "CACHE_KEY=deep-node-modules-${{ hashfiles('frontend/package-lock.json') }}" >> "$GITHUB_OUTPUT"
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: frontend/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
   

  linting:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libpangocairo-1.0-0
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: frontend/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
      - name: Lint the code
        run: npm run lint
      - name: Testing
        run: npm run test
      
      

 

        
